ttt_capstone_2015/ttk_capstone_2015/urls.py
"""
Definition of urls for ttt_capstone_2015.
"""

from datetime import datetime
from django.conf.urls import patterns, url
from graduate.forms import BootstrapAuthenticationForm

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',    
    url(r'^$', 'graduate.views.page1', name='page1'),
    url(r'^page-1', 'graduate.views.page1', name='page1'), #both home and page-1 are the same
    url(r'^page-2', 'graduate.views.page2', name='page2'), 
    url(r'^page-3', 'graduate.views.page3', name='page3'), 
    url(r'^confirmation', 'graduate.views.confirmation', name='confirmation'), 
    url(r'^pwemail/$', 'graduate.views.pwemail', name='pwemail'),
    url(r'^summary', 'graduate.views.summary', name='summary'),
    url(r'^login/$',
        'graduate.views.login',
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^alreadycompleted', 'graduate.views.alreadycompleted', name='alreadycompleted'), 
    
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
)

ttt_capstone_2015/graduate/models.py
from django.db import models


from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


#from simplecrypt import encrypt, decrypt
from fernet_fields import EncryptedTextField
from django.conf import settings
import binascii

# Create your models here.

class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            #date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(email,
            password=password,
            #date_of_birth=date_of_birth
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class Student(AbstractBaseUser): #models.Model
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )

    date_of_birth = models.DateField(null=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    #REQUIRED_FIELDS = ['email'] #YYYY-MM-DD

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
    batch_id = models.IntegerField(null=True)
    first_name = models.CharField(max_length=30, null=True)
    middle_name = models.CharField(max_length=30, null=True)
    last_name = models.CharField(max_length=30, null=True)
    suffix = models.CharField(max_length=30, null=True)
    preferred_first_name = models.CharField(max_length=30, null=True)
    birth_last_name = models.CharField(max_length=30, null=True)
    gender = models.CharField(max_length=45, null=True)
    birth_place = models.CharField(max_length=255, null=True)
    ethnicity = models.CharField(max_length=255, null=True)
    is_citizen = models.CharField(max_length=3, null=True)
    social_security = EncryptedTextField(null=True)
    denomination = models.IntegerField(null=True)
    start_term = models.CharField(max_length=255, null=True)
    student_load_intent = models.CharField(max_length=255, null=True)
    residency_status = models.CharField(max_length=255, null=True)
    planned_major = models.CharField(max_length=255, null=True)
    #level = models.CharField(max_length=3)    
    refered_by_name = models.CharField(max_length=255, null=True)
    refered_by_relationship = models.CharField(max_length=255, null=True)
    refered_by_name2 = models.CharField(max_length=255, null=True)
    refered_by_relationship2 = models.CharField(max_length=255, null=True)
    influence = models.CharField(max_length=255, null=True)
    employer = models.CharField(max_length=255, null=True)
    tuition_remission = models.NullBooleanField()    
    gi = models.NullBooleanField()
    citizenship_country = models.CharField(max_length=60, null=True)
    residence_country = models.CharField(max_length=60, null=True)
    alien_reg_no = models.CharField(max_length=15, null=True)
    is_international_student = models.CharField(max_length=3, null=True) 
    alien_status = models.CharField(max_length=30, null=True)
    employment_address_outside_us = models.BooleanField(default=0)
    submitted = models.IntegerField(default=0)
    internationalcheck = models.NullBooleanField()

    def __str__(self):
        return self.email

#would need to maintain hidden previously enter phone fields in order to do this, because of the updating problem. 
class Phone(models.Model):    
    student = models.ForeignKey(Student)
    phone = models.CharField(max_length=75, null=True)
    typeflag = models.CharField(max_length=255)

    def __str__(self):              
        return "%s %s" % (self.phone, self.typeflag)

class Address(models.Model):
    student = models.ForeignKey(Student)
    address1 = models.CharField(max_length=255, null=True)
    address2 = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    state = models.CharField(max_length=255, null=True)
    zipcode = models.CharField(max_length=32, null=True)
    country = models.CharField(max_length=255, null=True)
    typeflag = models.CharField(max_length=255) #'Flag for Student, Employer'

    def __str__(self):
        return "%s %s %s %s %s %s %s" % (self.address1, self.address2, self.city, self.state, self.zipcode, self.country, self.typeflag)


class Religions(models.Model):
    rid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class StudentLegal(models.Model):
    student = models.OneToOneField(Student, primary_key=True)
    reason = models.CharField(max_length=255)

    def __str__(self):
        return self.reason

class StudentPolicy(models.Model):
    student = models.OneToOneField(Student, primary_key=True)
    reason = models.CharField(max_length=255)

    def __str__(self):
        return self.student

class StudentRace(models.Model):
    student = models.ForeignKey(Student)
    raceid = models.CharField(max_length=255)

    def __str__(self):
        return self.raceid

    #maybe try making this a model form? 
class StudentUndergraduateInstitution(models.Model):
    student = models.ForeignKey(Student)
    name = models.CharField(max_length=255, null=True)
    ceeb = models.CharField(max_length=10, null=True)

    def __str__(self):
        return "%s %s" % (self.name, self.ceeb)

#class StudentUploads(models.Model):
#    ceeb = models.ForeignKey(Student)
#    name = models.CharField(max_length=255)

#    _data = models.TextField(
#            db_column='data',
#            blank=True)

#    def set_data(self, data):
#        self._data = base64.encodestring(data)

#    def get_data(self):
#        return base64.decodestring(self._data)

#    data = property(get_data, set_data)

#    def __str__(self):
#        return self.name        

class Race(models.Model):
    rid = models.AutoField(primary_key=True)
    race = models.CharField(max_length=255)
    
    def __str__(self):
        return self.race

class Majors(models.Model):
    mid = models.AutoField(primary_key=True)
    majors = models.CharField(max_length=255)
    
    def __str__(self):
        return self.majors

class Influences(models.Model):
    influence = models.CharField(max_length=255)
    
    def __str__(self):
        return self.influence

##DB inserts

### delete database and recreate empty in order to syncdb()
### yes to create damin = ttkoch@noctrl.edu - 1989-12-05 - password
### 
###
#pbkdf2_sha256$20000$gufZNBMAOxYp$fvYOSRqVLtMF1sK6hSaaXXDSrcsjvJ/gQFrQPIWIcu8=
#INSERT INTO `admissions.dev.capstone`.`graduate_race` (`rid`, `race`) VALUES (NULL, 'American Indian or Alaska Native'), (NULL, 'Asian'), (NULL, 'Black or African American'), (NULL, 'Native Hawaiian or Other Pacific Islander'), (NULL, 'White');
#INSERT INTO `admissions.dev.capstone`.`graduate_religions` (`rid`, `name`) VALUES (NULL, 'No Response'), (NULL, 'African Methodist Episcopal'), (NULL, 'Assembly of God'), (NULL, 'Baptist'), (NULL, 'Bible Church'), (NULL, 'Buddhist'), (NULL, 'Calvary Christian'), (NULL, 'Christian'), (NULL, 'Christian Orthodox'), (NULL, 'Church of Brethren'), (NULL, 'Church of Christ'), (NULL, 'Church of Christian Science'), (NULL, 'Church of God'), (NULL, 'Community'), (NULL, 'Congregational'), (NULL, 'Disciples of Christ'), (NULL, 'Episcopal'), (NULL, 'Evangelical'), (NULL, 'Evangelical Lutheran'), (NULL, 'Greek Orthodox'), (NULL, 'Hindu'), (NULL, 'Independent'), (NULL, 'Islam/Moslem'), (NULL, 'Jewish'), (NULL, 'Lutheran-Missouri'), (NULL, 'Lutheran-Other'), (NULL, 'Mennonite'), (NULL, 'Mormon'), (NULL, 'No Church Affiliation'), (NULL, 'Non-Affiliated Christian'), (NULL, 'Non-Christian'), (NULL, 'Non-Denominational'), (NULL, 'Other'), (NULL, 'Other Protestant'), (NULL, 'Pentecostal'), (NULL, 'Presbyterian'), (NULL, 'Reformed'), (NULL, 'Roman Catholic'), (NULL, 'Serbian Orthodox'), (NULL, 'Seventh Day Adventist'), (NULL, 'Unitarian/Universalist'), (NULL, 'United Church of Christ'), (NULL, 'United Methodist'), (NULL, 'United Presbyterian'), (NULL, 'Wesleyan');

ttt_capstone_2015/graduate/templates/app/alreadycompleted.html
{% load widget_tweaks %}
{% load staticfiles %}
<!DOCTYPE html><html>
   {% include 'app/header.html' %}
        <div class='container-fluid'>
            <div class='content row-fluid'>
                <div class='container'>
                  <div class='application'>
	<div class='inner-node'>
	<h1>Your Application has already been submitted.</h1>
	</div>
{% include 'app/footer.html' %}
</body>
</html>

ttt_capstone_2015/graduate/templates/app/confirmation.html
{% load widget_tweaks %}
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
{% include 'app/header.html' %}

<div class='application'>
    <div class='row-fluid'>
        <div class='mini-nav'>
                <a href="/" id="custom-breadcrumbs-home">Home</a> > <a href="/admission">Admission</a> >
        </div>
    </div>
    <div class='row-fluid'>
        <div class='inner-node'>
            <div class='row-fluid'>
            	<div class='container-fluid'>
            		<div class='span7'>
            			<div class='row-fluid'>
            				<h1 class='pg2-header'>Confirmation - THANK YOU FOR YOUR APPLICATION</h1>
            		    </div>
            		</div>
            		<div class='span11'>
            			<div class='row-fluid'>
            				<p>Congratulations, {{ first_name }}</p>
            				<p>You've successfully submitted your admission application to North Central College! Thank you for applying.</p>
            				<ul>
            				    <li>Print <a target="_blank" href="/summary/">your North Central College Admission Application</a> (as submitted)</li>
            				    <li>Print the <a target="_blank" href="https://northcentralcollege.edu/sites/default/files/Documents/admission/TranscriptRequest.pdf">Transcript Request Form</a> to submit to all institutions attended</li>
            				    <li>For international students, request official <a target="_blank" href="http://www.ets.org/toefl/ibt/scores/send/">TOEFL</a> and/or <a target="_blank" href="http://www.ielts.org/test_takers_information/getting_my_results/getting_my_results.aspx">IELTS</a> scores</li>
            				    <li>Submit your application <a target="_blank" href="https://northcentralcollege.edu/admission/upload-graduate-documents">materials here</a>
            				</ul>
            				<p>We look forward to reviewing your application, {{ first_name }}!</p>
            			</div>
            	    </div>
            	</div>
            </div>
        </div>
    </div>
</div> 

{% include 'app/footer.html' %}
</body>
</html>

ttt_capstone_2015/graduate/templates/app/footer.html
{% load staticfiles %}
       <div class="bottom hidden-phone">
            <div class="container-fluid">
                <div class="row-fluid">
                    <div class="container">
                        <div id="bottom">
                            <div id="footer">
                              <div id="footer-inner">
                                <div id="footer-left">
                                  <address>
                                    <span>North Central College</span>
                                    30 North Brainard Street<br>
                                    Naperville, IL 60540<br>
                                    630.637.5800
                                  </address>
                                </div>
                                <div id="footer-right">
                                  <ul id="utility">
                                    <li><a href="javascript:window.print()">Print</a></li>
                                    <li><a href="http://apply.northcentralcollege.edu.dev/graduate/page-2#">Email</a></li>
                                    <li><a class="a2a_dd" href="https://www.addtoany.com/share#url=http%3A%2F%2Fapply.northcentralcollege.edu.dev%2Fgraduate%2Fpage-2&title=North%20Central%20College&description=" aria-label="Share">Share</a>
                                    
                                    </li>
                                  </ul>
                                <div id="footer-mission"><p>North Central College prepares students to be informed,<br>involved, principled and productive citizens and leaders over their lifetime.</p></div>
                                <div id="footer-links">
                                  <ul>
                                    <li><a href="http://northcentralcollege.edu/content/contact-us">Contact Us</a></li>
                                    <li><a href="http://northcentralcollege.edu/content/mission">Mission Statement</a></li>
                                    <li><a href="http://northcentralcollege.edu/content/copyright">Copyright</a></li>
                                    <li><a href="http://northcentralcollege.edu/content/legal-notice">Legal Notice</a></li>
                                    <li><a href="http://northcentralcollege.edu/content/privacy-policy">Privacy Policy</a></li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                </div>
            </div>
        </div>



 

ttt_capstone_2015/graduate/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Django</h1>
    <p class="lead">Django is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Django gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://www.djangobook.com/en/2.0/index.html">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>The Python Package Index is a repository of software for the Python programming language.</p>
        <p><a class="btn btn-default" href="https://pypi.python.org/pypi">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Microsoft Azure</h2>
        <p>You can easily publish to Microsoft Azure using Python Tools for Visual Studio. Find out how you can host your application using a free trial today.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Learn more &raquo;</a></p>
    </div>
</div>

{% endblock %}

ttt_capstone_2015/graduate/templates/app/layout.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

{% include 'app/header.html' %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <div class="container-fluid">
            <div class="content row-fluid">
                <div class="container">
         <div class="application">
        <div class="row-fluid">
        {% block content %}{% endblock %}

    </div></div></div></div></div>



 {% include 'app/footer.html' %}



</body>
</html>

ttt_capstone_2015/graduate/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<div style="margin-left:30px;margin-top:20px;">
    <div class="col-md-12">
  
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Graduate Application Login</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Email Address: </label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password: </label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
       
    </div>
    
</div>

{% endblock %}


{% load staticfiles %}

ttt_capstone_2015/graduate/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}

ttt_capstone_2015/graduate/templates/app/page-1.html
{% load widget_tweaks %}
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

{% include 'app/header.html' %}
<script type="text/javascript" src="{% static 'app/scripts/graduate/page1.js' %}"></script>
    <style>
            #raceul ul{
                list-style: outside none none;                
            }
            #id_race input[type^="checkbox"] {
                float: right;
                margin-left: 10px;
            }
            #id_international_phonecheck, #id_internationalcheck{
                margin-right:10px;
            }
        </style>
    <div class="container-fluid">
            <div class="content row-fluid">
                <div class="container">
                  <form enctype="multipart/form-data" action="" method="post" name="applicationDefault">
                       {% csrf_token %}
                       {% include 'app/page1form.html' %}
                      <div class="row-fluid" id="navigation">
            <div class="span12">
                
<ul class="clearfix" id="saves">
    <span class="button-wrapper">
<input type="submit" class="multi-submit current-navigation" value="1" id="page1" name="page1"></span><span class="button-wrapper">
<input type="submit" class="multi-submit" value="Ahead to Page 2 &gt;&gt;" id="page2" name="page2"></span><span class="button-wrapper">
<input type="submit" class="multi-submit" value="3 &gt;&gt;" id="page3" name="page3">
<input type="submit" class="multi-submit" value="save page" id="save" name="save">
    </span>
   
</ul>          
            </div>
        </div>
                      </div>
                  </form>
                </div>
            </div>
        </div>

 {% include 'app/footer.html' %}



</body>
</html>

ttt_capstone_2015/graduate/templates/app/page-2.html
{% load widget_tweaks %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
 {% include 'app/header.html' %}
  <script type="text/javascript" src="{% static 'app/scripts/graduate/page2.js' %}"></script> 
  <script type="text/javascript" src="{% static 'app/scripts/graduate/jquery.formset.js' %}"></script> 

        <div class="container-fluid">
            <div class="content row-fluid">
                <div class="container">
                  <form name="applicationDefault" method="post" action="" enctype="multipart/form-data">
                      {% csrf_token %}
    <div class="application">
        <div class="row-fluid">
            <div class="mini-nav">
                    <a href="http://apply.northcentralcollege.edu.dev/" id="custom-breadcrumbs-home">Home</a> &gt; <a href="http://apply.northcentralcollege.edu.dev/admission">Admission</a> &gt;
            </div>
        </div>
       {% include 'app/page2form.html' %}
        <div id="navigation" class="row-fluid">
            <div class="span12">
                
<ul id="saves" class="clearfix">
    <span class="button-wrapper">
<input type="submit" name="page1" id="page1" value="&lt;&lt; 1" class="multi-submit">
    </span>
    <span class="button-wrapper">
<input type="submit" name="page2" id="page2" value="2" class="multi-submit current-navigation">
    </span>
    <span class="button-wrapper">
<input type="submit" name="page3" id="page3" value="Ahead to Page 3 &gt;&gt;" class="multi-submit">
<input type="submit" class="multi-submit" value="save page" id="save" name="save">
</span>
   
</ul>
            
            </div>
        </div>
    </div>
</form>
                </div>
            </div>
        </div>
 {% include 'app/footer.html' %}

</body>
</html>

ttt_capstone_2015/graduate/templates/app/page-3.html
{% load widget_tweaks %}
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
{% include 'app/header.html' %}
    <script type="text/javascript" src="{% static 'app/scripts/graduate/page1.js' %}"></script> 
    <script type="text/javascript" src="{% static 'app/scripts/graduate/page2.js' %}"></script> 
    <script type="text/javascript" src="{% static 'app/scripts/graduate/jquery.formset.js' %}"></script> 
    <style>
            #raceul ul{
                list-style: outside none none;                
            }
            #id_race input[type^="checkbox"] {
                float: right;
                margin-left: 10px;
            }
            #id_international_phonecheck, #id_internationalcheck{
                margin-right:10px;
            }
        </style>
    <div class="container-fluid">
            <div class="content row-fluid">
                <div class="container">
                <form enctype="multipart/form-data" action="" method="post" name="applicationDefault">
                  
                    {% csrf_token %}
                    {% include 'app/page1form.html' %}
                    {% include 'app/page2form.html' %}
                    <div class="row-fluid" id="navigation">
                    <div class="span12">
                
                    <ul class="clearfix" id="saves">
                    <span class="button-wrapper">
                        <input type="submit" class="multi-submit " value=" &lt;&lt; 1" id="page1" name="page1"></span><span class="button-wrapper">
                        <input type="submit" class="multi-submit" value=" &lt;&lt; Back to Page 2" id="page2" name="page2"></span><span class="button-wrapper">
                        <input type="submit" class="multi-submit current-navigation" value="3" id="page3" name="page3">
                        <input type="submit" class="multi-submit" value="save page" id="save" name="save">
                        <input type="submit" class="multi-submit" value="Submit Application" id="submit" name="submit">
                    </span>
                    </ul>          
                    </div>
                    </div>
                    </form>
            </div>                
		</div>
	 </div>
</div>

<!-- Print subform errors here -->
<div class='row-fluid'>
	<div class='container-fluid'>
		<div class='span12'>
			<div class='row-fluid'>
			    <p>This application must be electronically signed by the applicant by pressing submit below and is not valid if information is withheld or misinformation given. North Central College reserves the right to verify the information contained in this application by contacting prior educational institutions. Admission and credit earned by an invalid application will be canceled. If admitted, the applicant agrees to comply with all rules and regulations of the College. If you have changes to make before submitting your application for admission, please use the page navigation to return to previous pages.</p>
  			</div>
	    </div>
	</div>
</div>
    {% include 'app/footer.html' %}

</body>
</html>

ttt_capstone_2015/graduate/templates/app/pwemail.html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>This is a Heading</h1>
<p>This is a paragraph.</p>

</body>
</html> 